# -*- coding: utf-8 -*-
"""
Logistic (binary) version of Monte Carlo in Shen & Xiu style.
Based on your current linear script structure, but:
- y is binary generated by Bernoulli(sigmoid(X beta))
- Fit L1/L2 logistic with CV
- Use log-loss regret vs null(p=0.5) as Delta
- Use pseudo-R2_oos = 1 - LogLoss_model/LogLoss_null
"""

from __future__ import annotations
import os
import math
import numpy as np
import pandas as pd
from scipy.linalg import sqrtm
from joblib import Parallel, delayed

import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import log_loss


# -----------------------------
# Utilities: random orthogonal
# -----------------------------
def rand_ortho(p: int, rng: np.random.Generator) -> np.ndarray:
    A = rng.standard_normal((p, p))
    Q, R = np.linalg.qr(A)
    d = np.sign(np.diag(R))
    d[d == 0] = 1.0
    Q = Q * d
    return Q


def make_cov_mats(n: int, p: int, rho_1: float, seed: int = 1000):
    rng = np.random.default_rng(seed)

    idx = np.arange(n)
    Sigma_1 = rho_1 ** np.abs(idx[:, None] - idx[None, :])
    sqrtSigma_1 = sqrtm(Sigma_1).real

    eigen_Sigma_ep = 0.5 + rng.random(n)
    sqrtSigma_ep = np.diag(np.sqrt(eigen_Sigma_ep))

    U2 = rand_ortho(p, rng)
    eigen_Sigma_2 = 0.5 + rng.random(p)
    sqrtSigma_2 = U2 @ np.diag(np.sqrt(eigen_Sigma_2)) @ U2.T

    return sqrtSigma_1, sqrtSigma_ep, sqrtSigma_2


def sigmoid(z: np.ndarray) -> np.ndarray:
    # stable sigmoid
    z = np.clip(z, -30, 30)
    return 1.0 / (1.0 + np.exp(-z))


# -----------------------------
# Core single replication
# -----------------------------
def one_rep_logit(
    ii: int,
    R2: float,
    sparsity: float,
    n: int,
    p: int,
    tau_n: float,
    sigmabeta: float,
    sigmaep: float,
    sqrtSigma_1: np.ndarray,
    sqrtSigma_ep: np.ndarray,
    sqrtSigma_2: np.ndarray,
    n_oos: int,
    cv_folds: int,
    Cs_grid: np.ndarray,
):
    """
    One Monte Carlo replication for logistic DGP.
    Outputs:
      (R2, q, R2oos_lasso, R2oos_ridge, DeltaLasso, DeltaRidge)
    where Delta is based on log-loss regret vs null(p=0.5).
    """
    rng = np.random.default_rng(1000 + ii)

    # sparsity mask
    zero_loc = (rng.random(p) > (1.0 - sparsity)).astype(float)

    # keep same scaling rule as your linear code (signal strength knob)
    beta = (math.sqrt(1.0 / sparsity) * sigmabeta *
            rng.standard_normal(p) / math.sqrt(p / tau_n) *
            zero_loc).reshape(-1, 1)

    # design X
    X = sqrtSigma_1 @ rng.standard_normal((n, p)) @ sqrtSigma_2

    # OPTIONAL: add a small noise term in the index (like latent logistic with extra randomness)
    # If you want pure logistic, set add_latent_noise = False
    add_latent_noise = True
    if add_latent_noise:
        eps_latent = (sqrtSigma_ep @ (rng.standard_normal((n, 1)) * sigmaep))
        eta = (X @ beta) + eps_latent
    else:
        eta = (X @ beta)

    prob = sigmoid(eta).ravel()
    y = rng.binomial(1, prob, size=n).astype(int)

    # OOS
    X_oos = rng.standard_normal((n_oos, p)) @ sqrtSigma_2
    if add_latent_noise:
        eps_latent_oos = rng.standard_normal((n_oos, 1)) * sigmaep
        eta_oos = (X_oos @ beta) + eps_latent_oos
    else:
        eta_oos = (X_oos @ beta)
    prob_oos = sigmoid(eta_oos).ravel()
    y_oos = rng.binomial(1, prob_oos, size=n_oos).astype(int)

    # ---- L1 logistic (lasso) ----
    # Use saga for L1; standardize like glmnet default
    lasso = Pipeline([
        ("scaler", StandardScaler(with_mean=True, with_std=True)),
        ("model", LogisticRegressionCV(
            Cs=Cs_grid,
            cv=cv_folds,
            penalty="l1",
            solver="saga",
            scoring="neg_log_loss",
            fit_intercept=False,
            max_iter=5000,
            n_jobs=1,
            random_state=1000 + ii,
            refit=True,
        ))
    ])
    lasso.fit(X, y)
    p_lasso = lasso.predict_proba(X_oos)[:, 1]

    # ---- L2 logistic (ridge) ----
    # lbfgs supports l2 and is fast; you can also use saga for symmetry
    ridge = Pipeline([
        ("scaler", StandardScaler(with_mean=True, with_std=True)),
        ("model", LogisticRegressionCV(
            Cs=Cs_grid,
            cv=cv_folds,
            penalty="l2",
            solver="lbfgs",
            scoring="neg_log_loss",
            fit_intercept=False,
            max_iter=5000,
            n_jobs=1,
            random_state=1000 + ii,
            refit=True,
        ))
    ])
    ridge.fit(X, y)
    p_ridge = ridge.predict_proba(X_oos)[:, 1]

    # ---- Null baseline: always predict 0.5 ----
    p_null = np.full_like(p_lasso, 0.5, dtype=float)

    # log-loss (use eps for numerical stability)
    ll_lasso = log_loss(y_oos, p_lasso, labels=[0, 1])
    ll_ridge = log_loss(y_oos, p_ridge, labels=[0, 1])
    ll_null = log_loss(y_oos, p_null, labels=[0, 1])

    # Delta (log-loss regret scaled similarly)
    DeltaLasso = (p / n) * (tau_n ** -2) * (ll_lasso - ll_null)
    DeltaRidge = (p / n) * (tau_n ** -2) * (ll_ridge - ll_null)

    # pseudo-R2_oos
    R2oos_lasso = 1.0 - ll_lasso / ll_null
    R2oos_ridge = 1.0 - ll_ridge / ll_null

    return (R2, sparsity, R2oos_lasso, R2oos_ridge, DeltaLasso, DeltaRidge)


# -----------------------------
# Main driver
# -----------------------------
def main(
    R2: float,
    sparsity: float,
    n: int = 500,
    p: int = 300,
    mc_reps: int = 1000,
    n_oos: int = 10000,
    cv_folds: int = 10,
    n_jobs: int = -1,
    out_dir: str = "weaksimu_logit_py",
):
    os.makedirs(out_dir, exist_ok=True)

    tau_n = R2 / (1.0 - R2)
    sigmaep = 1.0
    sigmabeta = 1.0
    rho_1 = 0.5

    sqrtSigma_1, sqrtSigma_ep, sqrtSigma_2 = make_cov_mats(n, p, rho_1, seed=1000)

    # Cs grid: C is inverse of regularization strength.
    # Smaller C => stronger penalty. Use broad range.
    Cs_grid = np.logspace(-4, 4, 40)

    rows = Parallel(n_jobs=n_jobs, verbose=5)(
        delayed(one_rep_logit)(
            ii=ii,
            R2=R2,
            sparsity=sparsity,
            n=n,
            p=p,
            tau_n=tau_n,
            sigmabeta=sigmabeta,
            sigmaep=sigmaep,
            sqrtSigma_1=sqrtSigma_1,
            sqrtSigma_ep=sqrtSigma_ep,
            sqrtSigma_2=sqrtSigma_2,
            n_oos=n_oos,
            cv_folds=cv_folds,
            Cs_grid=Cs_grid,
        )
        for ii in range(1, mc_reps + 1)
    )

    df = pd.DataFrame(rows, columns=["R2", "q", "R2oos_lasso", "R2oos_ridge", "DeltaLasso", "DeltaRidge"])
    out_path = os.path.join(out_dir, "exam_logit.csv")
    df.to_csv(out_path, index=False)
    return df


def make_figure_and_table(dfs: dict, out_dir: str = "weaksimu_logit_py"):
    """
    Same layout as your linear figure:
    top: Ridge Delta histogram
    bottom: Lasso Delta histogram
    """
    os.makedirs(out_dir, exist_ok=True)

    setups = [(0.05, 0.2), (0.05, 0.8), (0.5, 0.2)]
    fig, axes = plt.subplots(2, 3, figsize=(12, 7), sharey=False)

    for j, key in enumerate(setups):
        df = dfs[key]
        dr = df["DeltaRidge"].to_numpy()
        dl = df["DeltaLasso"].to_numpy()

        ax = axes[0, j]
        ax.hist(dr, bins=60, density=True)
        ax.axvline(0.0, linestyle="--")
        ax.set_title(rf"$R^2={int(key[0]*100)}\%,\, q={key[1]}$ (logit)")
        ax.set_xlim(-2, 2)

        ax2 = axes[1, j]
        ax2.hist(dl, bins=60, density=True)
        ax2.axvline(0.0, linestyle="--")
        ax2.set_title(rf"$R^2={int(key[0]*100)}\%,\, q={key[1]}$ (logit)")
        ax2.set_xlim(-2, 2)

    fig.suptitle("Logistic Monte Carlo: Ridge vs Lasso (Delta based on log-loss regret)")
    fig.tight_layout(rect=[0, 0.02, 1, 0.95])
    fig_path = os.path.join(out_dir, "figure_logit.png")
    fig.savefig(fig_path, dpi=200)
    plt.close(fig)

    table_rows = []
    for (R2, q) in setups:
        df = dfs[(R2, q)]
        for model in ["Lasso", "Ridge"]:
            d = df["DeltaLasso"] if model == "Lasso" else df["DeltaRidge"]
            d = d.to_numpy()
            q1, q2, q3 = np.quantile(d, [0.25, 0.50, 0.75])
            n_zero = int(np.sum(np.isclose(d, 0.0, atol=1e-12)))
            table_rows.append({
                "q": q,
                "SignalKnob(R2)": int(R2 * 100),
                "Model": model,
                "Q1": q1,
                "Q2": q2,
                "Q3": q3,
                "#Zero": n_zero
            })

    tab = pd.DataFrame(table_rows)
    tab_path = os.path.join(out_dir, "table_logit.csv")
    tab.to_csv(tab_path, index=False)

    return fig_path, tab_path, tab


if __name__ == "__main__":
    dfs = {}
    for (R2, q) in [(0.05, 0.2), (0.05, 0.8), (0.5, 0.2)]:
        print(f"Running logistic: R2={R2}, q={q}")
        df = main(R2=R2, sparsity=q, n=500, p=300, mc_reps=1000, n_oos=10000, cv_folds=10, n_jobs=-1)
        dfs[(R2, q)] = df

    fig_path, tab_path, tab = make_figure_and_table(dfs)
    print("Saved:", fig_path)
    print("Saved:", tab_path)
    print(tab)
